using IronPython.Hosting;
using Microsoft.Scripting.Hosting;
using System.Diagnostics;
using System.IO;
using System.Collections.Generic;

namespace TranslationLib
{
    public class Grammar
    {
        public List<Rule> Rules
        {
            get
            {
                var r = new List<Rule>();
                foreach (var s in rules)
                {
                    r.Add(new Rule(s));
                }
                return r;
            }
        }

        private string isFunction(string w)
        {
            for (int i = 0; i < function_words_tags.GetLength(1); i++)
                for (int j = 0; j < function_words_tags.GetLength(2); j++)
                {
                    if (w == function_words_tags[i][j]) return function_words_tags[i][j];
                }
            return "";
        }

        private string noun_stem(string x)
        {
            ScriptEngine engine = Python.CreateEngine();
            ScriptScope scope = engine.CreateScope();

            engine.ExecuteFile("../../../TranslationLib/noun_stem.py", scope);
            dynamic function = scope.GetVariable("noun_stem");
            dynamic result = function(x);
            return result.ToString();
        }

        private string verb_stem(string x)
        {
            var fileName = "C:/Users/Sonya/Desktop/VCR/TranslationSystem_git/TranslationSystem/TranslationLib/verb_stem.py";
            ProcessStartInfo start = new ProcessStartInfo(@"C:\Users\Sonya\AppData\Local\Programs\Python\Python36\python.exe", fileName);
            start.Arguments = string.Format(fileName + " " + x);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    process.WaitForExit();
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script                   
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                    return result.Substring(0, result.Length - 2);
                }
            }
        }

        public void POS_Tagging(Lexicon lx)
        {
            /* Grammar for the statement language is:
            #   S  -> P is AR Ns | P is A | P Is | P Ts P
            #   AR -> a | an*/
            var wlist = lx.getAll();
            foreach (var w in wlist)
            {
                if ('A' <= w.Word[0] && w.Word[0] <= 'Z')
                    w.POSTags.Add("P");

                string f = isFunction(w.Word);
                if (!string.IsNullOrEmpty(f))
                {
                    w.POSTags.Add(f);
                }
            }

            if (wlist[1].Word == "is")
            {
                if (wlist[2].Word == "a" || wlist[2].Word == "an")
                    if (!wlist[3].POSTags.Contains("N")) wlist[3].POSTags.Add("N");
                    else
                         if (!wlist[2].POSTags.Contains("A")) wlist[3].POSTags.Add("A");
            }
            else
            {
                string stem = verb_stem(wlist[1].Word);
                if (wlist.Count == 2)
                {
                    wlist[1].Word = stem;
                    if (!wlist[1].POSTags.Contains("I")) wlist[1].POSTags.Add("I");
                }
                else
                if (wlist[2].POSTags.Contains("P"))
                {
                    wlist[1].Word = stem;
                    if (!wlist[1].POSTags.Contains("T")) wlist[1].POSTags.Add("T");
                }
            }

            lx.changeLx(wlist);
        }

        string[] rules = new string[] {
            "S -> WHAT QP OF NP WITH NP QP | WHAT QP OF NP | WHAT QP OF NP ABOUT NP | WHOSE NP QP | WHOSE NP | WHOSE NP OF NP",
            "QP -> VP",
            "VP -> I | T NP | BE A | BE NP | VP AND VP | LIKE NP",
            "NP -> P | AR Nom | Nom",
            "Nom -> AN | AN Rel",
            "AN -> N | A AN",
            "Rel -> WHO VP | NP T",
            "N -> 'Ns' | 'Np'",
            "I -> 'Is' | 'Ip'",
            "T -> 'Ts' | 'Tp'",
            "A -> 'A'",
            "P -> 'P'",
            "BE -> 'BEs' | 'BEp'",
            "AR -> 'AR'",
            "WHO -> 'WHO'",
            "WHAT -> 'WHICH' | 'WHAT'",
            "AND -> 'AND'",
            "OR -> 'OR'",
            "OF -> 'OF'",
            "LIKE -> 'LIKE'",
            "WITH -> 'WITH'",
            "ABOUT -> 'ABOUT'",
            "WHOSE -> 'WHOSE'"
        };

        string[][] function_words_tags = new string[][] {
           new string[] {"BEs", "is", "was" },
           new string[] { "BEp", "are", "were" },
           new string[] {"AR", "a", "an" },
           new string[] {"AND", "and"  },
           new string[] {"WHO", "Who" },
           new string[] {"WHICH", "Which" },
           new string[] {"WHAT" , "What" },
           new string[] {"OR", "or" },
           new string[] {"OF", "of"},
           new string[] {"LIKE", "like"},
           new string[] {"WITH", "with"},
           new string[] {"ABOUT", "about"},
           new string[] { "WHOSE", "Whose" }
           };
    }
}
