use MIGRATION_CENTER

CREATE TABLE  LAST_NAME(	
    ID int NOT NULL Identity(1, 1), 
	NAME_RUS VARCHAR(64) NOT NULL, 
	NAME_ENG VARCHAR(64) NOT NULL, 
	CONSTRAINT LAST_NAME_PK PRIMARY KEY (ID),
    CONSTRAINT LAST_NAME_CON UNIQUE (NAME_RUS, NAME_ENG)
)

CREATE TABLE  MIDDLE_NAME(	
    ID int NOT NULL Identity(1, 1), 
	NAME_RUS VARCHAR(64) NOT NULL, 
	NAME_ENG VARCHAR(64) NOT NULL, 
	 CONSTRAINT MIDDLE_NAME_PK PRIMARY KEY (ID),
	 CONSTRAINT MIDDLE_NAME_UK1 UNIQUE (NAME_RUS, NAME_ENG)
)

CREATE TABLE FIRST_NAME(
    ID int NOT NULL Identity(1, 1), 
	NAME_RUS VARCHAR(64) NOT NULL, 
	NAME_ENG VARCHAR(64) NOT NULL, 
	CONSTRAINT "FIRST_NAME_PK" PRIMARY KEY (ID),
	CONSTRAINT "FIRST_NAME_CON" UNIQUE (NAME_RUS, "NAME_ENG")
)

CREATE TABLE  EXPERT 
   (	ID int NOT NULL Identity(1,1), 
	FIRST_NAME_ID int, 
	LAST_NAME_ID int NOT NULL, 
	MIDDLE_NAME_ID int, 
	DEGREE VARCHAR(32), 
	 CONSTRAINT EXPERT_PK PRIMARY KEY (ID)
)

CREATE TABLE  E_MAIL(	
    ID_EXPERT int NOT NULL Identity(1, 1), 
	MAIL VARCHAR(64) NOT NULL, 
	 CONSTRAINT "E_MAIL_UK1" UNIQUE (MAIL)
)

CREATE TABLE PUBLICATION(	
    ID int Identity(1,1) NOT NULL, 
	DESCRIPTION_RUS VARCHAR(512), 
	DESCRIPTION_ENG VARCHAR(512), 
	TITLE VARCHAR(256) NOT NULL, 
	REFERENCE VARCHAR(256), 
	CONSTRAINT PUBLICATION_PK PRIMARY KEY (ID)
)

CREATE TABLE  EXPERT_PUBLICATION(
	ID_EXPERT int NOT NULL, 
	ID_PUBLICATION int NOT NULL
)

CREATE TABLE  TELEPHONE(	
    ID_EXPERT int NOT NULL, 
	PHONE VARCHAR(32) NOT NULL
)

ALTER TABLE  "EXPERT" ADD CONSTRAINT "EXPERT_FK" FOREIGN KEY ("FIRST_NAME_ID")
	  REFERENCES  "FIRST_NAME" ("ID") 

ALTER TABLE  "EXPERT" ADD CONSTRAINT "EXPERT_FK1" FOREIGN KEY ("LAST_NAME_ID")
	  REFERENCES  "LAST_NAME" ("ID") 

ALTER TABLE  "EXPERT" ADD CONSTRAINT "EXPERT_FK2" FOREIGN KEY ("MIDDLE_NAME_ID")
	  REFERENCES  "MIDDLE_NAME" ("ID") 

ALTER TABLE  "EXPERT_PUBLICATION" ADD CONSTRAINT "EXPERT_PUBLICATION_FK1" FOREIGN KEY ("ID_EXPERT")
	  REFERENCES  "EXPERT" ("ID") 

ALTER TABLE  "EXPERT_PUBLICATION" ADD CONSTRAINT "EXPERT_PUBLICATION_FK2" FOREIGN KEY ("ID_PUBLICATION")
	  REFERENCES  "PUBLICATION" ("ID") 

ALTER TABLE  "E_MAIL" ADD CONSTRAINT "E_MAIL_FK" FOREIGN KEY ("ID_EXPERT")
	  REFERENCES  "EXPERT" ("ID") 

ALTER TABLE  "TELEPHONE" ADD CONSTRAINT "TELEPHONE_FK" FOREIGN KEY ("ID_EXPERT")
	  REFERENCES  "EXPERT" ("ID") 
